/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProxyServer_CONSTANTS_H
#define ProxyServer_CONSTANTS_H

#include "ProxyServer_types.h"

namespace proxyserver {

class ProxyServerConstants {
 public:
  ProxyServerConstants();

};

extern const ProxyServerConstants g_ProxyServer_constants;

} // namespace

#endif
