/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ProxyServer_constants.h"

namespace proxyserver {

const ProxyServerConstants g_ProxyServer_constants;

ProxyServerConstants::ProxyServerConstants() {
}

} // namespace

